platform :ios, '12.0'

target 'MRGLaunchImageViewController_Example' do
  use_frameworks!
  pod 'MRGLaunchImageViewController', :path => '../'

  target 'MRGLaunchImageViewController_Tests' do
    inherit! :search_paths
  end
end
