source 'https://github.com/CocoaPods/Specs.git'

target 'MRGLaunchImageViewController_Example', :exclusive => true do
  pod "MRGLaunchImageViewController", :path => "../"
end

target 'MRGLaunchImageViewController_Tests', :exclusive => true do
  pod "MRGLaunchImageViewController", :path => "../"
end
